"use client";

import { useState } from "react";
import { signIn } from "next-auth/react";
import { BrandLockup, SiemensWordmark } from "@/components/Brand";
import { SIEMENS_PETROL, SIEMENS_DARK } from "@/lib/theme";

// ── "How it works" content ─────────────────────────────────────────────────
// Each step maps to the real data flow and names the codebase files
// a developer would open to verify it.

const STEPS = [
  {
    step: "1",
    label: "Detect",
    tagline: "LED status — which core(s) failed",
    bullets: [
      "BMC deterministic test pattern execution emits to POST /api/test-runs → stored in test_runs collection (≈ SQL table with embedded components[] array — no JOIN needed)",
      "Failure rate > 10% triggers an alert document in alerts collection and queues diagnostic enrichment in the background",
      "LED state changes pushed live via Server-Sent Events (backed by MongoDB Change Streams — ≈ SQL TRIGGER / LISTEN-NOTIFY)",
    ],
    codeRefs: [
      { label: "test_runs route", path: "backend/app/routes/test_runs.py" },
      { label: "embeddings service", path: "backend/app/services/embeddings.py" },
      { label: "SSE endpoint", path: "backend/app/routes/telemetry.py" },
    ],
  },
  {
    step: "2",
    label: "Root cause",
    tagline: "3-stage fault isolation chain",
    bullets: [
      "Stage 1 — Failure Prediction: aggregation pipeline ($match → $unwind → $group) computes per-component failure rates over a 24 h window",
      "Stage 2 — Root Cause: automated fault isolation pipeline — RAG context injected from Atlas $vectorSearch (find_similar_failures tool, 1024-dim index) to surface similar historical incidents",
      "Stage 3 — Work Order: prioritized, traceable repair order generated by referencing retrieved incidents",
    ],
    codeRefs: [
      { label: "agents/failure_prediction.py", path: "backend/app/agents/failure_prediction.py" },
      { label: "agents/root_cause.py", path: "backend/app/agents/root_cause.py" },
      { label: "agents/work_order.py", path: "backend/app/agents/work_order.py" },
      { label: "tools/find_similar_failures.py", path: "backend/app/tools/find_similar_failures.py" },
      { label: "services/llm.py", path: "backend/app/services/llm.py" },
    ],
  },
  {
    step: "3",
    label: "Act",
    tagline: "Automated repair recommendations",
    bullets: [
      "RootCauseCard shows hypothesis, confidence bar, evidence list, and next diagnostic steps",
      "WorkOrderCard shows P1–P4 priority, ordered repair steps, required parts, and safety flags",
      "All runs stored in agent_runs collection — $aggregate pipelines mine recurring root causes across the fleet (the Knowledge Base panel)",
    ],
    codeRefs: [
      { label: "alerts/page.tsx", path: "frontend/app/alerts/page.tsx" },
      { label: "components/RootCauseCard", path: "frontend/components/RootCauseCard.tsx" },
      { label: "components/WorkOrderCard", path: "frontend/components/WorkOrderCard.tsx" },
      { label: "agents route (chain + KB)", path: "backend/app/routes/agents.py" },
    ],
  },
];

const SQL_CONCEPTS = [
  { mongo: "Collection", sql: "Table" },
  { mongo: "Document", sql: "Row" },
  { mongo: "$match", sql: "WHERE" },
  { mongo: "$group", sql: "GROUP BY" },
  { mongo: "$lookup", sql: "LEFT JOIN" },
  { mongo: "Change Stream", sql: "TRIGGER" },
];

// ── Component ──────────────────────────────────────────────────────────────

export default function LoginPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [expandedStep, setExpandedStep] = useState<string | null>(null);

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError("");
    const result = await signIn("credentials", {
      email: email.trim(),
      password,
      redirect: false,
    });
    setLoading(false);
    if (result?.error) {
      setError("Invalid credentials. Contact your administrator for access.");
    } else {
      window.location.href = "/";
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center px-4 py-8" style={{ background: "#F4F7F9" }}>
      <div className="w-full max-w-5xl">

        {/* Brand header */}
        <div className="flex justify-center mb-6">
          <BrandLockup wordmarkClass="text-lg" siemensSize={18} />
        </div>

        <div className="flex flex-col lg:flex-row gap-6 items-start">

          {/* ── Left: How it works ────────────────────────────────────────── */}
          <div className="flex-1 min-w-0">
            <div className="bg-white border border-slate-200 rounded-xl shadow-sm overflow-hidden">
              <div className="h-1" style={{ background: SIEMENS_PETROL }} />
              <div className="px-5 py-5">
                <h2 className="text-sm font-bold text-slate-800 mb-1">How it works</h2>
                <p className="text-xs text-slate-400 mb-4">
                  SoC fleet health monitoring — from deterministic test telemetry to fault work orders
                </p>

                {/* Steps */}
                <div className="space-y-2">
                  {STEPS.map((s) => {
                    const isOpen = expandedStep === s.step;
                    return (
                      <div
                        key={s.step}
                        className="rounded-lg border border-slate-200 overflow-hidden"
                      >
                        <button
                          onClick={() => setExpandedStep(isOpen ? null : s.step)}
                          className="w-full flex items-start gap-3 px-3 py-3 text-left hover:bg-slate-50 transition-colors"
                        >
                          <span
                            className="w-5 h-5 shrink-0 rounded-full text-white text-[10px] font-bold flex items-center justify-center mt-0.5"
                            style={{ background: SIEMENS_PETROL }}
                          >
                            {s.step}
                          </span>
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2 flex-wrap">
                              <span className="text-sm font-semibold text-slate-800">{s.label}</span>
                            </div>
                            <p className="text-[11px] text-slate-500 mt-0.5">{s.tagline}</p>
                          </div>
                          <span className="text-slate-300 text-[10px] shrink-0 mt-1">{isOpen ? "▾" : "▸"}</span>
                        </button>

                        {isOpen && (
                          <div className="border-t border-slate-100 px-4 py-3 bg-slate-50 space-y-3">
                            {/* Bullets */}
                            <ul className="space-y-1.5">
                              {s.bullets.map((b, i) => (
                                <li key={i} className="flex items-start gap-2 text-[11px] text-slate-600 leading-relaxed">
                                  <span className="text-slate-300 shrink-0 mt-0.5">·</span>
                                  <span>{b}</span>
                                </li>
                              ))}
                            </ul>

                            {/* Code refs */}
                            <div>
                              <p className="text-[10px] font-semibold text-slate-400 uppercase tracking-wide mb-1.5">
                                Look here in the codebase
                              </p>
                              <div className="flex flex-wrap gap-1.5">
                                {s.codeRefs.map((ref) => (
                                  <span
                                    key={ref.path}
                                    title={ref.path}
                                    className="text-[10px] font-mono px-2 py-0.5 rounded border border-slate-200 bg-white text-slate-500"
                                  >
                                    {ref.label}
                                  </span>
                                ))}
                              </div>
                            </div>
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>

                {/* Platform strip */}
                <div className="mt-4 pt-4 border-t border-slate-100">
                  <div
                    className="rounded-xl px-4 py-3"
                    style={{ background: SIEMENS_DARK }}
                  >
                    <p className="text-[10px] font-semibold uppercase tracking-widest mb-3" style={{ color: SIEMENS_PETROL }}>
                      Platform
                    </p>
                    {/* Central hub */}
                    <div
                      className="rounded-lg px-3 py-2 mb-2.5"
                      style={{ background: `${SIEMENS_PETROL}22`, border: `1px solid ${SIEMENS_PETROL}55` }}
                    >
                      <div className="flex items-center justify-between">
                        <p className="text-[12px] font-bold" style={{ color: SIEMENS_PETROL }}>MongoDB Atlas</p>
                        <span className="text-[10px] font-mono text-slate-500">pulse_bmc</span>
                      </div>
                      <p className="text-[10px] text-slate-400 mt-0.5">
                        Document store · Change Streams · Vector Search — one cluster, three jobs
                      </p>
                    </div>
                    {/* Flanking tools */}
                    <div className="grid grid-cols-2 gap-2">
                      <div className="rounded-lg px-2.5 py-2" style={{ background: "#ffffff08", border: "1px solid #ffffff14" }}>
                        <p className="text-[11px] font-semibold text-slate-300">Vector Search</p>
                        <p className="text-[10px] text-slate-500 font-mono mt-0.5">1024-dim · cosine similarity</p>
                      </div>
                      <div className="rounded-lg px-2.5 py-2" style={{ background: "#ffffff08", border: "1px solid #ffffff14" }}>
                        <p className="text-[11px] font-semibold text-slate-300">Diagnostic Chain</p>
                        <p className="text-[10px] text-slate-500 font-mono mt-0.5">predict → rca → work order</p>
                      </div>
                    </div>
                  </div>
                </div>

                {/* SQL concept grid */}
                <div className="mt-3">
                  <p className="text-[10px] font-semibold text-slate-400 uppercase tracking-widest mb-2">
                    SQL background? MongoDB in familiar terms
                  </p>
                  <div className="grid grid-cols-3 gap-1.5">
                    {SQL_CONCEPTS.map((c) => (
                      <div
                        key={c.mongo}
                        className="rounded-lg border-l-2 bg-white border border-slate-100 px-2 py-1.5"
                        style={{ borderLeftColor: SIEMENS_PETROL }}
                      >
                        <p className="text-[11px] font-mono font-bold text-slate-700">{c.mongo}</p>
                        <p className="text-[10px] text-slate-400 mt-0.5">{c.sql}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* ── Right: Login form ─────────────────────────────────────────── */}
          <div className="w-full lg:w-80 shrink-0">
            <div className="bg-white border border-slate-200 rounded-xl shadow-sm overflow-hidden">
              <div className="h-1" style={{ background: SIEMENS_PETROL }} />
              <div className="px-6 py-6">
                <h1 className="text-lg font-bold text-slate-900">Sign in</h1>
                <p className="text-xs text-slate-500 mt-1">
                  SoC fleet health monitoring — deterministic test telemetry to fault work orders
                </p>

                <form onSubmit={onSubmit} className="space-y-3 mt-5">
                  <div>
                    <label className="block text-xs font-semibold text-slate-600 mb-1">Email</label>
                    <input
                      type="email"
                      value={email}
                      onChange={(e) => { setEmail(e.target.value); setError(""); }}
                      autoComplete="email"
                      className="w-full text-sm border border-slate-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2"
                      style={{ accentColor: SIEMENS_PETROL }}
                      placeholder="you@company.com"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-slate-600 mb-1">Password</label>
                    <input
                      type="password"
                      value={password}
                      onChange={(e) => { setPassword(e.target.value); setError(""); }}
                      autoComplete="current-password"
                      className="w-full text-sm border border-slate-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2"
                      placeholder="••••••••"
                    />
                  </div>

                  {error && <p className="text-xs text-red-600">{error}</p>}

                  <button
                    type="submit"
                    disabled={loading}
                    className="w-full text-sm font-semibold text-white rounded-lg py-2 transition-opacity hover:opacity-90 disabled:opacity-60"
                    style={{ background: SIEMENS_PETROL }}
                  >
                    {loading ? "Signing in…" : "Sign in"}
                  </button>
                </form>

                <p className="mt-4 text-[11px] text-slate-500">
                  Demo access is provisioned by your administrator. Atlas and AI keys never leave the server.
                </p>

                {/* What you'll see after sign in */}
                <div className="mt-4 space-y-1.5">
                  <p className="text-[10px] font-semibold text-slate-400 uppercase tracking-wide">After sign in</p>
                  {[
                    { dot: "bg-green-500", label: "Fleet Overview", sub: "click Start live demo, then watch the LED grid pulse" },
                    { dot: "bg-red-500", label: "Open Alerts", sub: "fault analysis + work orders" },
                    { dot: "bg-slate-300", label: "Architecture", sub: "schema + data flow diagrams" },
                    { dot: "bg-slate-300", label: "Explore", sub: "live query browser" },
                  ].map((item) => (
                    <div key={item.label} className="flex items-center gap-2 text-[11px]">
                      <span className={`w-2 h-2 rounded-full shrink-0 ${item.dot}`} />
                      <span className="font-medium text-slate-700">{item.label}</span>
                      <span className="text-slate-400">— {item.sub}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            <div className="mt-4 rounded-xl border border-slate-200 bg-white px-4 py-3 flex flex-col items-center gap-2 shadow-sm">
              <div className="flex items-center gap-2">
                <span
                  style={{ fontSize: "9px", color: "#00ED64" }}
                >●</span>
                <span className="text-xs text-slate-500">SoCPulse — Powered by</span>
                <span className="text-xs font-bold" style={{ color: "#00ED64" }}>MongoDB Atlas</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="inline-block shrink-0 leading-none">
                  <SiemensWordmark size={12} />
                </span>
                <span className="text-slate-300 text-xs">·</span>
                <span className="text-[11px] text-slate-500">Software</span>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
