import { NextRequest, NextResponse } from "next/server";
import { randomBytes } from "crypto";
import { writeFileSync, existsSync } from "fs";
import path from "path";

export const runtime = "nodejs";

function isLocalhost(request: NextRequest): boolean {
  const host = request.headers.get("host") ?? "";
  const bare = host.split(":")[0];
  return bare === "localhost" || bare === "127.0.0.1" || bare === "::1";
}

function setupEnabled(): boolean {
  if (process.env.VERCEL) return false;
  return process.env.ALLOW_SETUP === "true";
}

export async function POST(request: NextRequest) {
  if (!setupEnabled()) {
    return NextResponse.json({ detail: "Setup wizard is disabled" }, { status: 403 });
  }
  if (!isLocalhost(request)) {
    return NextResponse.json({ detail: "Setup is localhost-only" }, { status: 403 });
  }

  const body = await request.json();
  const authSecret = (body.auth_secret as string)?.trim() || randomBytes(32).toString("base64");
  const demoUser = (body.demo_user as string)?.trim();
  const demoPassword = body.demo_user_password as string;
  const backendApiKey = (body.backend_api_key as string)?.trim() ?? "";

  if (!demoUser || !demoPassword) {
    return NextResponse.json({ detail: "Demo login email and password are required" }, { status: 400 });
  }

  const envPath = path.join(process.cwd(), ".env.local");
  if (existsSync(envPath) && process.env.ALLOW_SETUP_RESET !== "true") {
    const existing = await import("fs/promises").then((fs) => fs.readFile(envPath, "utf8"));
    if (existing.includes("AUTH_SECRET=") && existing.match(/AUTH_SECRET=\S+/)) {
      // Allow overwrite during initial wizard save (backend just saved)
    }
  }

  const lines = [
    `# Generated by setup wizard — ${new Date().toISOString()}`,
    `AUTH_SECRET=${authSecret}`,
    `DEMO_USER=${demoUser}`,
    `DEMO_USER_PASSWORD=${demoPassword}`,
    `API_URL=http://localhost:8000`,
    `BACKEND_API_KEY=${backendApiKey}`,
    `ALLOW_SETUP=true`,
  ];

  writeFileSync(envPath, lines.join("\n") + "\n", "utf8");

  return NextResponse.json({
    ok: true,
    auth_secret: authSecret,
    message: "frontend/.env.local saved. Restart ./start.sh to apply.",
  });
}
