"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import ConceptBar from "@/components/ConceptBar";
import QueryTooltip from "@/components/QueryTooltip";
import RootCauseCard from "@/components/RootCauseCard";
import WorkOrderCard from "@/components/WorkOrderCard";
import RetrievedContextPanel from "@/components/RetrievedContextPanel";
import LedIndicator from "@/components/LedIndicator";
import GuidedTour, { TourCard, WhyBox, Pill } from "@/components/GuidedTour";
import { api, SSE_URL } from "@/lib/api";
import { fmtDateTime, fmtRelative } from "@/lib/time";
import type { Step } from "react-joyride";

interface Alert {
  id: string;
  device_id: string;
  summary: string;
  severity: string;
  status: string;
  failure_rate: number;
  triggered_at: string;
}

interface RootCause {
  alert_id: string;
  root_cause_hypothesis: string;
  evidence: string[];
  confidence: number;
  alternative_hypotheses: string[];
  next_diagnostic_steps: string[];
  retrieved_context_summary: string;
}

interface WorkOrder {
  title: string;
  priority: "P1" | "P2" | "P3" | "P4";
  assigned_technician: string;
  repair_steps: string[];
  estimated_duration_minutes: number;
  required_parts: string[];
  safety_notes: string[];
  historical_basis: string;
  originating_alert_id: string;
}

interface RetrievedDoc {
  collection: string;
  doc_id: string;
  similarity?: number;
  summary: string;
}

interface ChainResult {
  prediction: Record<string, unknown>;
  root_cause: RootCause;
  work_order: WorkOrder;
  agent_run_id: string;
  cached?: boolean;
  cached_at?: string;
}

interface KnowledgeBase {
  total_runs: number;
  latest_run_at: string | null;
  top_hypotheses: Array<{ id: string; count: number; avg_confidence: number; devices: string[]; last_seen: string }>;
  at_risk_components: Array<{ id: string; appearances: number; avg_failure_rate: number; error_codes: string[] }>;
  priority_distribution: Array<{ priority: string; count: number }>;
}

const SEVERITY_COLORS: Record<string, string> = {
  critical: "border-rose-800/60 bg-rose-950/10",
  high:     "border-amber-800/50 bg-amber-950/10",
  medium:   "border-yellow-800/40 bg-yellow-950/10",
  low:      "border-slate-700/60 bg-slate-900/20",
};

const ALERTS_TOUR_STEPS: Step[] = [
  {
    target: "#alert-list",
    title: "Alerts — auto-generated by Atlas",
    content: (
      <TourCard>
        <p>
          Each alert here was created automatically when a device's failure rate crossed 10%.
          No separate alerting service — MongoDB evaluates the threshold using a{" "}
          <Pill>$group</Pill> aggregation on every test run insert.
        </p>
        <p>
          The alert document in the <Pill>alerts</Pill> collection stores the device ID,
          failure rate, severity, and timestamp — all in one place.
        </p>
        <WhyBox>
          SQL equivalent: a stored procedure or trigger + a separate alerts table.
          Here it's one aggregation query on the existing indexed data.
        </WhyBox>
      </TourCard>
    ),
  },
  {
    target: "#run-ai-btn",
    title: "Run AI Analysis — three-stage pipeline",
    content: (
      <TourCard>
        <p>
          Clicking this button runs three AI agents in sequence against your Atlas data:
        </p>
        <p>
          <strong>Stage 1 — Predict:</strong> aggregates failure rates per component to
          identify what's trending toward failure.
        </p>
        <p>
          <strong>Stage 2 — Root Cause:</strong> uses <strong>Atlas Vector Search</strong> to
          find past failures that <em>feel similar</em> to this one — even if error codes differ.
        </p>
        <p>
          <strong>Stage 3 — Work Order:</strong> synthesizes a prioritized repair plan
          grounded in the retrieved historical incidents.
        </p>
        <p className="text-gray-300 text-xs">Takes ~20–30 seconds. Click it now while reading the next step.</p>
      </TourCard>
    ),
  },
  {
    target: "#retrieved-context-panel",
    title: "RAG: retrieving past incidents",
    content: (
      <TourCard>
        <p>
          This panel shows what the AI retrieved from Atlas before writing the root cause analysis.
          Each row is a past failure document that was semantically similar to the current alert.
        </p>
        <p>
          <strong>How it works:</strong> Voyage AI converted each test run's failure description
          into a 1,024-dimensional vector stored alongside the document. A{" "}
          <Pill>$vectorSearch</Pill> query finds the nearest vectors to the new failure.
        </p>
        <p className="text-gray-300 text-xs">
          "Nearest" means similar in meaning — not just matching keywords or error codes.
        </p>
        <WhyBox>
          Vector Search runs inside Atlas alongside your operational data. No Pinecone,
          no ETL, no separate vector store to operate.
        </WhyBox>
      </TourCard>
    ),
  },
  {
    target: "#rca-wo-grid",
    title: "Root Cause + Work Order",
    content: (
      <TourCard>
        <p>
          <strong>Root Cause card (left):</strong> the AI's hypothesis with a confidence score,
          evidence list, and next diagnostic steps — all grounded in the retrieved incidents.
        </p>
        <p>
          <strong>Work Order card (right):</strong> a prioritized repair checklist with
          estimated duration, required parts, and safety warnings for any destructive steps.
        </p>
        <p>
          Both outputs are structured Pydantic objects logged to the{" "}
          <Pill>agent_runs</Pill> collection in Atlas — fully auditable and queryable.
        </p>
        <WhyBox>
          The entire agent run — inputs, retrieved docs, LLM outputs — lives in one Atlas
          document. One query to replay any diagnosis.
        </WhyBox>
      </TourCard>
    ),
  },
];

export default function AlertsPage() {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [queryInfo, setQueryInfo] = useState<Record<string, unknown> | null>(null);
  const [running, setRunning] = useState<string | null>(null);
  const [results, setResults] = useState<Record<string, ChainResult>>({});
  const [agentRuns, setAgentRuns] = useState<Record<string, Record<string, unknown>>>({});
  const [kb, setKb] = useState<KnowledgeBase | null>(null);
  const [kbOpen, setKbOpen] = useState(false);
  const [lastCapture, setLastCapture] = useState<{ msg: string; ts: string } | null>(null);
  const [newAlertIds, setNewAlertIds] = useState<Set<string>>(new Set());
  const knownIds = useRef<Set<string>>(new Set());
  const lastRefreshAt = useRef<number>(0);

  const refresh = useCallback(async () => {
    const res = await api.alerts("open");
    const incoming: Alert[] = res.data ?? [];
    lastRefreshAt.current = Date.now();

    // Flag new IDs for the "just arrived" highlight
    const fresh = incoming.filter((a) => !knownIds.current.has(a.id)).map((a) => a.id);
    if (knownIds.current.size > 0 && fresh.length > 0) {
      setNewAlertIds((prev) => new Set([...prev, ...fresh]));
      setTimeout(() => {
        setNewAlertIds((prev) => {
          const next = new Set(prev);
          fresh.forEach((id) => next.delete(id));
          return next;
        });
      }, 4000);
    }
    incoming.forEach((a) => knownIds.current.add(a.id));

    // Smart merge — update existing cards in-place, prepend genuinely new ones.
    // Cards never change position so expanded AI results stay stable.
    setAlerts((prev) => {
      const incomingMap = new Map(incoming.map((a) => [a.id, a]));
      // Update existing alerts in-place (failure_rate may tick up)
      const updated = prev
        .filter((a) => incomingMap.has(a.id))          // drop resolved ones
        .map((a) => ({ ...a, ...incomingMap.get(a.id)! })); // patch changed fields
      const existingIds = new Set(prev.map((a) => a.id));
      const brandNew = incoming.filter((a) => !existingIds.has(a.id));
      return [...brandNew, ...updated];                 // new alerts prepend
    });

    setQueryInfo(res.query_info ?? null);
  }, []);

  useEffect(() => {
    refresh();
    api.knowledgeBase().then((k) => setKb(k as KnowledgeBase)).catch(() => {});
  }, [refresh]);

  // Live: update capture ticker from SSE; debounce list refresh to avoid
  // rapid re-renders when multiple alert events arrive in quick succession.
  useEffect(() => {
    const es = new EventSource(SSE_URL);
    es.onmessage = (e) => {
      const payload = JSON.parse(e.data);
      if (payload.connected) return;
      const ts = new Date().toLocaleTimeString("en-US", { hour12: false });
      if (payload.event_type === "alert") {
        setLastCapture({ msg: payload.message || `Alert fired on ${payload.device_id}`, ts });
        // Debounce: skip if we refreshed within the last 3 seconds
        if (Date.now() - lastRefreshAt.current > 3000) {
          refresh();
        }
      } else if (payload.device_id && payload.status === "fail") {
        setLastCapture({ msg: `Loopback FAIL captured on ${payload.device_id}`, ts });
      } else if (payload.device_id) {
        setLastCapture({ msg: `Loopback captured on ${payload.device_id}`, ts });
      }
    };
    return () => es.close();
  }, [refresh]);

  const runChain = async (alert: Alert, forceRefresh = false) => {
    setRunning(alert.id);
    try {
      const res = await api.agentChain(alert.id, alert.device_id, forceRefresh) as ChainResult;
      setResults((prev) => ({ ...prev, [alert.id]: res }));

      if (res.agent_run_id) {
        const run = await api.agentRun(res.agent_run_id);
        setAgentRuns((prev) => ({ ...prev, [alert.id]: run }));
      }
      // Refresh knowledge base after each completed analysis
      api.knowledgeBase().then((k) => setKb(k as KnowledgeBase)).catch(() => {});
    } catch (e) {
      console.error(e);
    } finally {
      setRunning(null);
    }
  };

  const firstAlertWithResult = alerts.find((a) => results[a.id]);

  return (
    <div>
      <ConceptBar />
      <main className="max-w-6xl mx-auto px-4 py-6">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-2xl font-bold text-white">Open Alerts</h1>
            <div className="text-sm text-gray-400 mt-1 flex items-center gap-1 flex-wrap">
              Alerts generated when failure rate exceeds 10% threshold
              {queryInfo && <QueryTooltip queryInfo={queryInfo as Parameters<typeof QueryTooltip>[0]["queryInfo"]} label="query" />}
            </div>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-xs border border-gray-600 px-2 py-1 rounded text-gray-300">
              {alerts.length} open · <span className="font-mono text-yellow-400">alerts</span> collection
            </span>
            <GuidedTour
              steps={ALERTS_TOUR_STEPS}
              label="Alerts Tour"
              stepCount={ALERTS_TOUR_STEPS.length}
            />
          </div>
        </div>

        {/* Live capture indicator — proves alerts arrive in real time */}
        <div className="flex items-center gap-2 mb-5 text-xs">
          <span className="flex items-center gap-1.5 text-emerald-400">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse shadow-[0_0_5px_rgba(74,222,128,0.7)]" />
            Live
          </span>
          <span className="text-slate-500">·</span>
          <span className="text-slate-400 font-mono truncate">
            {lastCapture ? (
              <>
                <span className="text-slate-500">{lastCapture.ts}</span>{" "}
                {lastCapture.msg}
              </>
            ) : (
              "Listening for loopback captures from Atlas…"
            )}
          </span>
        </div>

        {alerts.length === 0 && (
          <div className="text-gray-300 text-sm text-center py-12">
            No open alerts. Fleet is healthy ✓
          </div>
        )}

        <div id="alert-list" className="space-y-6">
          {alerts.map((alert, idx) => {
            const result = results[alert.id];
            const agentRun = agentRuns[alert.id];
            const isRunning = running === alert.id;

            const isNew = newAlertIds.has(alert.id);

            return (
              <div
                key={alert.id}
                className={`border rounded-lg overflow-hidden transition-all ${SEVERITY_COLORS[alert.severity] ?? "border-gray-700"} ${isNew ? "ring-2 ring-emerald-500/60 shadow-[0_0_16px_rgba(16,185,129,0.25)]" : ""}`}
              >
                {isNew && (
                  <div className="bg-emerald-500/15 text-emerald-300 text-[11px] px-4 py-1 font-medium">
                    ● Just arrived — captured live from Atlas
                  </div>
                )}
                {/* Alert header */}
                <div className="p-4">
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex items-start gap-3">
                      <LedIndicator state="red" size="md" />
                      <div>
                        <p className="text-sm font-medium text-white">{alert.device_id}</p>
                        <p className="text-xs text-gray-400 mt-0.5">{alert.summary}</p>
                        <div className="flex items-center gap-3 mt-2 text-xs text-gray-400">
                          <span className="text-rose-300 font-mono">{(alert.failure_rate * 100).toFixed(1)}% failure rate</span>
                          <span title={fmtDateTime(alert.triggered_at)}>{fmtRelative(alert.triggered_at)}</span>
                          <span className="capitalize border border-gray-700 px-1.5 py-0.5 rounded">{alert.severity}</span>
                        </div>
                      </div>
                    </div>

                    <div className="shrink-0 flex flex-col items-end gap-1.5">
                      {!result ? (
                        <button
                          id={idx === 0 ? "run-ai-btn" : undefined}
                          onClick={() => runChain(alert)}
                          disabled={!!running}
                          className="text-xs bg-slate-800 border border-slate-600 text-slate-200 px-3.5 py-2 rounded-lg hover:bg-slate-700 hover:border-slate-500 transition-all disabled:opacity-40 font-medium"
                        >
                          {isRunning ? (
                            <span className="flex items-center gap-2">
                              <span className="w-3 h-3 border border-slate-400 border-t-transparent rounded-full animate-spin" />
                              <span className="text-slate-300">Analysing…</span>
                            </span>
                          ) : (
                            <span className="flex items-center gap-1.5">
                              <span className="text-indigo-400">✦</span> Run AI Analysis
                            </span>
                          )}
                        </button>
                      ) : (
                        <div className="flex items-center gap-2">
                          {result.cached && (
                            <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-900/40 border border-emerald-700/50 text-emerald-300 font-medium">
                              ⚡ Cached
                            </span>
                          )}
                          <button
                            onClick={() => runChain(alert, true)}
                            disabled={!!running}
                            title="Re-run analysis (bypass cache)"
                            className="text-[11px] text-slate-400 hover:text-slate-200 border border-slate-700 px-2.5 py-1 rounded transition-colors disabled:opacity-40"
                          >
                            {isRunning ? "Running…" : "⟳ Re-analyze"}
                          </button>
                        </div>
                      )}
                    </div>
                  </div>
                </div>

                {/* AI Results */}
                {result && (
                  <div className="border-t border-slate-800/60 p-4 space-y-4 bg-slate-950/40">
                    <div className="flex items-center gap-2 text-xs text-slate-400">
                      <span className="text-indigo-400">✦</span>
                      <span className="text-slate-400">AI analysis complete</span>
                      <span className="font-mono text-slate-400 ml-1">run …{result.agent_run_id?.slice(-8)}</span>
                    </div>

                    {/* RAG retrieved context */}
                    <div id={firstAlertWithResult?.id === alert.id ? "retrieved-context-panel" : undefined}>
                      {Array.isArray(agentRun?.retrieved_documents) && (
                        <RetrievedContextPanel
                          docs={agentRun.retrieved_documents as RetrievedDoc[]}
                          agentRunId={result.agent_run_id}
                        />
                      )}
                    </div>

                    <div id={firstAlertWithResult?.id === alert.id ? "rca-wo-grid" : undefined}
                         className="grid grid-cols-1 xl:grid-cols-2 gap-6">
                      <div>
                        <p className="text-xs text-slate-300 mb-2 font-semibold uppercase tracking-wide">Root Cause Analysis</p>
                        <RootCauseCard rca={result.root_cause} />
                      </div>
                      <div>
                        <p className="text-xs text-slate-300 mb-2 font-semibold uppercase tracking-wide">Work Order</p>
                        <WorkOrderCard wo={result.work_order} />
                      </div>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
        {/* Knowledge Base */}
        {kb && kb.total_runs > 0 && (
          <div className="mt-8 border border-slate-700/60 rounded-lg overflow-hidden">
            <button
              onClick={() => setKbOpen((o) => !o)}
              className="w-full flex items-center justify-between px-4 py-3 bg-slate-800/60 hover:bg-slate-700/50 transition-colors"
            >
              <span className="flex items-center gap-2.5 text-sm text-slate-200 font-medium">
                <span className="text-indigo-400">◈</span>
                AI Knowledge Base
                <span className="text-xs font-normal text-slate-400">— patterns extracted from {kb.total_runs} stored analysis run{kb.total_runs !== 1 ? "s" : ""}</span>
              </span>
              <span className="text-slate-400 text-xs">{kbOpen ? "▾ hide" : "▸ show"}</span>
            </button>

            {kbOpen && (
              <div className="bg-slate-900/60 p-4 space-y-6">
                <p className="text-xs text-slate-400">
                  Every AI analysis is stored in the <span className="font-mono text-yellow-300">agent_runs</span> collection in Atlas.
                  These patterns are extracted by aggregating across all past runs — the knowledge base grows automatically with each new analysis.
                  Future RCA prompts are also seeded with the top hypotheses here.
                </p>

                {/* Top root cause hypotheses */}
                {kb.top_hypotheses.length > 0 && (
                  <div>
                    <h3 className="text-xs font-semibold text-slate-300 uppercase tracking-wide mb-3">Recurring Root Cause Hypotheses</h3>
                    <div className="space-y-2">
                      {kb.top_hypotheses.slice(0, 5).map((h, i) => (
                        <div key={i} className="flex items-start gap-3 text-xs bg-slate-800/50 border border-slate-700/40 rounded-lg px-3 py-2.5">
                          <span className="text-slate-500 shrink-0 tabular-nums w-4">{i + 1}.</span>
                          <span className="text-slate-200 flex-1 leading-relaxed">{h.id || "—"}</span>
                          <div className="shrink-0 flex items-center gap-2 text-slate-400">
                            <span className="text-emerald-400 font-medium">{(h.avg_confidence * 100).toFixed(0)}%</span>
                            <span className="text-slate-600">·</span>
                            <span>{h.count}×</span>
                            <span className="text-slate-600">·</span>
                            <span>{h.devices.length} device{h.devices.length !== 1 ? "s" : ""}</span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* At-risk components + priority distribution side by side */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {kb.at_risk_components.length > 0 && (
                    <div>
                      <h3 className="text-xs font-semibold text-slate-300 uppercase tracking-wide mb-3">Most Flagged Components</h3>
                      <div className="space-y-1.5">
                        {kb.at_risk_components.slice(0, 6).map((c, i) => (
                          <div key={i} className="flex items-center gap-2 text-xs">
                            <span className="font-mono text-blue-300 w-28 shrink-0 truncate">{c.id || "—"}</span>
                            <div className="flex-1 bg-slate-800 rounded-full h-1.5">
                              <div
                                className="bg-rose-500 h-1.5 rounded-full"
                                style={{ width: `${Math.min(100, (c.avg_failure_rate ?? 0) * 100)}%` }}
                              />
                            </div>
                            <span className="text-slate-400 w-12 text-right">{c.appearances}×</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {kb.priority_distribution.length > 0 && (
                    <div>
                      <h3 className="text-xs font-semibold text-slate-300 uppercase tracking-wide mb-3">Work Order Priority Distribution</h3>
                      <div className="space-y-1.5">
                        {kb.priority_distribution.map((p) => {
                          const max = Math.max(...kb.priority_distribution.map((x) => x.count));
                          const colors: Record<string, string> = { P1: "bg-rose-500", P2: "bg-amber-500", P3: "bg-yellow-500", P4: "bg-slate-500" };
                          return (
                            <div key={p.priority} className="flex items-center gap-2 text-xs">
                              <span className="font-mono text-slate-300 w-7 shrink-0">{p.priority}</span>
                              <div className="flex-1 bg-slate-800 rounded-full h-1.5">
                                <div
                                  className={`${colors[p.priority] ?? "bg-slate-500"} h-1.5 rounded-full`}
                                  style={{ width: `${(p.count / max) * 100}%` }}
                                />
                              </div>
                              <span className="text-slate-400 w-6 text-right">{p.count}</span>
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        )}
      </main>
    </div>
  );
}
